trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: 'Install dependencies'

  - script: |
      ng build --configuration production
    displayName: 'Build Angular app'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist/angular-realworld-example-app' # <-- adjust this based on your project
      ArtifactName: 'angularapp'
      publishLocation: 'Container'
    displayName: 'Publish Artifact'
